### ISSUE TITLE
Broken import in version 2.0.0

### ISSUE THREAD

**Issue by utkarshp** [rocky/pytracer#8]
## Description

Unable to import tracer

## How to Reproduce

Just do `import tracer`

## Output Given
```
>python
Python 3.9.6 (default, Jul 30 2021, 16:35:19)
[GCC 7.5.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import tracer
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/utkarsh/.conda/envs/trepan/lib/python3.9/site-packages/tracer/__init__.py", line 10, in <module>
    from tracer.tracer import (
ModuleNotFoundError: No module named 'tracer.tracer'
```

## Expected behavior

Successful import

## Environment

- xdis version: output from `pip show xdis`
```
Name: xdis
Version: 6.1.1
Summary: Python cross-version byte-code library and disassembler
Home-page:
Author:
Author-email: Rocky Bernstein <rb@dustyfeet.com>
License: GPL
Location: /home/utkarsh/.conda/envs/trepan/lib/python3.9/site-packages
Requires: click, six
Required-by: pyficache, trepan3k
```
- Python version:
```
>python -c "import sys; print(sys.version)"
3.9.6 (default, Jul 30 2021, 16:35:19)
[GCC 7.5.0]
```
- OS and Version: [e.g. Ubuntu bionic]
 GNU/Linux x86_64

## Workarounds

Downgrading tracer to version 0.3.2 works

## Priority
Important for the new version 2.0.0

**Comment by rocky** [comment]
The problem is not in pytracer or xdis, but trepan3k.  If you install the current master branch from github, you will be fine.  Sometime before the end of year I will release a new trepan3k.

**Comment by nejmeijer** [comment]
As mentioned in Trepan-Debuggers/python3-trepan#71, the wheels on PyPI were updated and I just confirmed that `tracer` imports without problems now. This issue can be closed too.
